spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surveys_db
    username: surveys_admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.default_schema: dev
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: debug