spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surveys_db
    username: surveys_admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect